# Generated by Django 4.1.5 on 2023-02-19 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='zimmer_id',
            new_name='zimmer_cust_no',
        ),
    ]
