# Generated by Django 4.1.5 on 2023-02-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_invoice_billed_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceproduct',
            name='commission',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoiceproduct',
            name='extended_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
