# Generated by Django 4.1.5 on 2023-02-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_invoiceproduct_commission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceproduct',
            name='commission',
            field=models.FloatField(),
        ),
    ]
