# Generated by Django 4.1.5 on 2023-02-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_invoiceproduct_commission_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceproduct',
            name='extended_price',
            field=models.FloatField(),
        ),
    ]
